image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - docker info
    # - sudo add-apt-repository universe
    # - sudo add-apt-repository multiverse
    # - sudo apt-get update
    # - sudo apt-get upgrade
  script:
    - echo setting up env $DYNAMIC_ENV_VAR
    - docker ps
    - sudo docker image prune -f
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
    # - docker image push leehankue/nginx-hostname
    # - docker login -u 도커허브ID -p 비밀번호
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml push --with-registry-auth
    - docker images
  only:
    - main
  tags:
    - nginx-hostname

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml hostname --with-registry-auth
    # - docker service update hostname_web

  only:
    - main
  tags:
    - nginx-hostname
